apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../

configMapGenerator:
  - name: external-secrets-config
    behavior: replace
    literals:
      - ENVIRONMENT=dev
      - AWS_REGION=us-east-1

patches:
  # Reduce refresh interval for dev environment
  - patch: |-
      - op: replace
        path: /spec/refreshInterval
        value: 5m
    target:
      kind: ExternalSecret

commonLabels:
  environment: dev
