apiVersion: v1
kind: Namespace
metadata:
  name: autolytiq
  labels:
    app.kubernetes.io/name: autolytiq
    app.kubernetes.io/part-of: autolytiq-desk-studio
    # Enable Istio sidecar injection for all pods in this namespace
    istio-injection: enabled
