apiVersion: apps/v1
kind: Deployment
metadata:
  name: settings-service
  namespace: autolytiq
  labels:
    app: settings-service
    tier: backend
    version: stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: settings-service
  template:
    metadata:
      labels:
        app: settings-service
        tier: backend
        version: stable
      annotations:
        sidecar.istio.io/inject: 'true'
        sidecar.istio.io/proxyCPU: '50m'
        sidecar.istio.io/proxyCPULimit: '300m'
        sidecar.istio.io/proxyMemory: '64Mi'
        sidecar.istio.io/proxyMemoryLimit: '128Mi'
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8090'
        prometheus.io/path: '/metrics'
    spec:
      containers:
        - name: settings-service
          image: 730335214557.dkr.ecr.us-east-1.amazonaws.com/autolytiq/settings-service:v1.0.0
          ports:
            - containerPort: 8090
              name: http
          env:
            - name: PORT
              value: '8090'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: autolytiq-secrets
                  key: DATABASE_URL
            - name: DB_HOST
              value: 'autolytiq-prod.cluster-cj0mc26mutcf.us-east-1.rds.amazonaws.com'
            - name: DB_PORT
              value: '5432'
            - name: DB_USER
              value: 'autolytiq_admin'
            - name: DB_PASSWORD
              value: 'MzWbvgV8oU8xrfDYBg8GqsyzjzvxwcHS'
            - name: DB_NAME
              value: 'autolytiq'
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '500m'
          livenessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: settings-service
  namespace: autolytiq
  labels:
    app: settings-service
spec:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: http
  selector:
    app: settings-service
