apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: autolytiq-staging

resources:
  - ../../base

commonLabels:
  environment: staging

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment

configMapGenerator:
  - name: autolytiq-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - ENABLE_SWAGGER=true

images:
  - name: autolytiq/api-gateway
    newTag: staging
  - name: autolytiq/auth-service
    newTag: staging
  - name: autolytiq/deal-service
    newTag: staging
  - name: autolytiq/customer-service
    newTag: staging
  - name: autolytiq/inventory-service
    newTag: staging
  - name: autolytiq/email-service
    newTag: staging
  - name: autolytiq/user-service
    newTag: staging
  - name: autolytiq/config-service
    newTag: staging
