apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: autolytiq-prod

resources:
  - ../../base
  - hpa.yaml
  - pdb.yaml

commonLabels:
  environment: prod

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "200m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"
    target:
      kind: Deployment
  # Update LOG_LEVEL in configmap for prod
  - patch: |-
      - op: replace
        path: /data/LOG_LEVEL
        value: "warn"
      - op: add
        path: /data/ENABLE_SWAGGER
        value: "false"
    target:
      kind: ConfigMap
      name: autolytiq-config
  # Disable Istio sidecar injection for now (can be enabled later)
  - patch: |-
      - op: replace
        path: /spec/template/metadata/annotations/sidecar.istio.io~1inject
        value: "false"
    target:
      kind: Deployment

images:
  - name: autolytiq/api-gateway
    newName: 730335214557.dkr.ecr.us-east-1.amazonaws.com/autolytiq/api-gateway
    newTag: v1.0.4
  - name: autolytiq/auth-service
    newName: 730335214557.dkr.ecr.us-east-1.amazonaws.com/autolytiq/auth-service
    newTag: v1.0.1
  - name: autolytiq/deal-service
    newName: 730335214557.dkr.ecr.us-east-1.amazonaws.com/autolytiq/deal-service
    newTag: v1.0.1
  - name: autolytiq/customer-service
    newName: 730335214557.dkr.ecr.us-east-1.amazonaws.com/autolytiq/customer-service
    newTag: v1.0.1
  - name: autolytiq/inventory-service
    newName: 730335214557.dkr.ecr.us-east-1.amazonaws.com/autolytiq/inventory-service
    newTag: v1.0.1
  - name: autolytiq/email-service
    newName: 730335214557.dkr.ecr.us-east-1.amazonaws.com/autolytiq/email-service
    newTag: v1.0.1
  - name: autolytiq/user-service
    newName: 730335214557.dkr.ecr.us-east-1.amazonaws.com/autolytiq/user-service
    newTag: v1.0.1
  - name: autolytiq/config-service
    newName: 730335214557.dkr.ecr.us-east-1.amazonaws.com/autolytiq/config-service
    newTag: v1.0.1
