apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: autolytiq-prod

resources:
  - ../../base
  - hpa.yaml
  - pdb.yaml

commonLabels:
  environment: prod

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "200m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"
    target:
      kind: Deployment

configMapGenerator:
  - name: autolytiq-config
    behavior: merge
    literals:
      - LOG_LEVEL=warn
      - ENABLE_SWAGGER=false

images:
  - name: autolytiq/api-gateway
    newTag: prod
  - name: autolytiq/auth-service
    newTag: prod
  - name: autolytiq/deal-service
    newTag: prod
  - name: autolytiq/customer-service
    newTag: prod
  - name: autolytiq/inventory-service
    newTag: prod
  - name: autolytiq/email-service
    newTag: prod
  - name: autolytiq/user-service
    newTag: prod
  - name: autolytiq/config-service
    newTag: prod
