apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
  - istio-namespace.yaml
  - peer-authentication.yaml
  - authorization-policy.yaml
  - destination-rules.yaml
  - virtual-services.yaml
  - monitoring.yaml

commonLabels:
  app.kubernetes.io/part-of: autolytiq-service-mesh
  app.kubernetes.io/managed-by: kustomize
# Note: istio-installation.yaml is not included here as it should be
# applied using istioctl: istioctl install -f istio-installation.yaml
