apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus-rbac.yaml
  - prometheus-config.yaml
  - prometheus-rules.yaml
  - prometheus-deployment.yaml
  - alertmanager.yaml
  - grafana-config.yaml
  - grafana-dashboards.yaml
  - grafana-deployment.yaml
  - servicemonitors.yaml

commonLabels:
  app.kubernetes.io/part-of: autolytiq-monitoring
  app.kubernetes.io/managed-by: kustomize

images:
  - name: prom/prometheus
    newTag: v2.47.0
  - name: prom/alertmanager
    newTag: v0.26.0
  - name: grafana/grafana
    newTag: '10.2.0'
